// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvpArchitecture.Data.Models.Contacts;
using UIKit;

namespace MvpArchitecture.iOS.Areas.Contacts
{
	public partial class ContactsTableViewCell : UITableViewCell
	{
		public ContactsTableViewCell (IntPtr handle) : base (handle)
		{
		}

		public void Update( ContactListItemViewModel contactList )
		{
			ContactName.Text = contactList.Name;
			ContactTypes.Text = contactList.Types;
		}
	}
}
