// This file has been autogenerated from a class added in the UI designer.

using System;
using Features.Playground.Core.Classes;
using Features.Playground.iOS.Classes;
using Features.Playground.iOS.ViewControllers.Maintenance.List;
using Foundation;
using UIKit;

namespace Features.Playground.iOS.ViewControllers.Maintenance
{
	public partial class MaintenanceEmbeddedTableViewController : UITableViewController
	{
		public MaintenanceEmbeddedTableViewController( IntPtr handle ) : base( handle )
		{
		}

		public override void ViewDidLoad( )
		{
			base.ViewDidLoad( );

			ConfigureIcons( );
		}

		public override void RowSelected( UITableView tableView, NSIndexPath indexPath )
		{
			MaintenanceListViewController2 destinationVc = StoryboardHelper.GetViewController<MaintenanceListViewController2>( "Main", "MaintenanceListViewController" );
			UITableViewCell cellSelected = tableView.CellAt( indexPath );

			if ( cellSelected.Equals( RequestedTableViewCell ) )
			{
				destinationVc.SetMaintenanceStatus( Enums.MaintenanceStatus.Requested );
			}
			else if ( cellSelected.Equals( IncompleteTableViewCell ) )
			{
				destinationVc.SetMaintenanceStatus( Enums.MaintenanceStatus.Incomplete );
			}
			else if ( cellSelected.Equals( CompletedTableViewCell ) )
			{
				destinationVc.SetMaintenanceStatus( Enums.MaintenanceStatus.Complete );
			}
			else if ( cellSelected.Equals( CreateMaintenanceTableViewCell ) )
			{
				return;
			}
			else
			{
				return;
			}

			NavigationController.PushViewController( destinationVc, true );
		}

		private void ConfigureIcons( )
		{
			CreateMaintenanceTableViewCell.BackgroundColor = UIColor.Clear.FromHex( "#4ac06b" );
			CreateLabel.TextColor = UIColor.Clear.FromHex( "#fff" );
			CreateIcon.ToColour( UIColor.Clear.FromHex( "#fff" ) );

			RequestedIcon.ToColour( UIColor.Clear.FromHex( "#0cb6ea" ) );
			IncompleteIcon.ToColour( UIColor.Clear.FromHex( "#414c50" ) );
			CompletedIcon.ToColour( UIColor.Clear.FromHex( "#4ac06b" ) );
		}
	}
}