// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Features.Playground.iOS.ViewControllers.Maintenance
{
	public partial class MaintenanceHubViewController : UIViewController
	{
		public MaintenanceHubViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
