// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using UIKit;

namespace PullToRefresh.iOS
{
	public partial class DynamicViewController : UIViewController
	{
		public DynamicViewController( IntPtr handle ) : base( handle )
		{
		}

		public override void ViewDidLoad( )
		{
			base.ViewDidLoad( );

			DynamicTableView.Source = new DynamicSource( );

			//DynamicTableView.RefreshControl = new UIRefreshControl( );
			//DynamicTableView.RefreshControl.ValueChanged += ( sender, e ) =>
			//{
			//	DynamicTableView.RefreshControl.EndRefreshing( );	
			//};
		}
	}
}
