// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PullToRefresh.iOS
{
	public partial class StaticTableViewController : UITableViewController
	{
		public StaticTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
