// This file has been autogenerated from a class added in the UI designer.

using System;
using Features.Playground.Core.Models;
using Features.Playground.iOS.Classes;
using Features.Playground.iOS.Views.Text;
using UIKit;

namespace Features.Playground.iOS.Views.Cells
{
	public partial class MaintenanceTableViewCell2 : UITableViewCell
	{
		private static UIColor Red = UIColor.Clear.FromHex( "#ce4837" );

		public MaintenanceTableViewCell2( IntPtr handle ) : base( handle )
		{
		}

		public void UpdateViews( MaintenanceListItem maintenanceListItem )
		{
			TitleLabel.TextColor = maintenanceListItem.IsOverDue ? Red : PrimaryCellLabel.TextColour;
			DueDateLabel.TextColor = maintenanceListItem.IsOverDue ? Red : SecondaryCellLabel.TextColour;

			TitleLabel.Text = maintenanceListItem.Title;
			DueDateLabel.Text = maintenanceListItem.DueDate.ToString( "dd MMMMM yyyy" );
		}
	}
}
