// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PullToRefresh.iOS
{
	public partial class DynamicCell : UITableViewCell
	{
		public DynamicCell( IntPtr handle ) : base( handle )
		{
		}

		public void UpdateViews( string cellLabel )
		{
			TextLabel.Text = cellLabel;
		}
	}
}
