// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Features.Playground.iOS.ViewControllers.Maintenance.Details;
using Foundation;
using UIKit;

namespace Features.Playground.iOS.FlowLayouts.Maintenance
{
	public class MaintenanceDetailsImageCollectionViewDelegateFlowLayout : UICollectionViewDelegateFlowLayout
	{
		private nfloat _itemsDisplayedOnScreen;
		private readonly MaintenanceDetailsViewController _parentController;

		private ICollectionViewLayoutConfigHelper LayoutConfig => _parentController.ImagesCollectionViewLayoutConfig;

		public MaintenanceDetailsImageCollectionViewDelegateFlowLayout( MaintenanceDetailsViewController maintenanceDetailsViewController )
		{
			_parentController = maintenanceDetailsViewController;

			UpdateNumberOfItemsDisplayedOnScreen( );
		}

		public override CGSize GetSizeForItem( UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath )
		{
			nfloat cellWidth = LayoutConfig.GetCellWidthRelativeToCollectionViewWidth( collectionView, _itemsDisplayedOnScreen );

			_parentController.SetCollectionViewHeight( cellWidth );

			return new CGSize( cellWidth, cellWidth );
		}

		public override nfloat GetMinimumInteritemSpacingForSection( UICollectionView collectionView, UICollectionViewLayout layout, nint section )
		{
			return LayoutConfig.CellSpacing;
		}

		public override nfloat GetMinimumLineSpacingForSection( UICollectionView collectionView, UICollectionViewLayout layout, nint section )
		{
			return LayoutConfig.LineSpacing;
		}

		public void UpdateNumberOfItemsDisplayedOnScreen( )
		{
			_itemsDisplayedOnScreen = UIDevice.CurrentDevice.Orientation.IsLandscape( )
				? LayoutConfig.ItemsDisplayedOnScreenLandscape
				: LayoutConfig.ItemsDisplayedOnScreenPortrait;
		}
	}
}